[profile.default]
solc_version = '0.8.15'
auto_detect_solc = false
optimizer = true
optimizer_runs = 200
ffi = true
fuzz_runs = 1_000
remappings = [
    "forge-std=lib/forge-std/src/",
    "foundry-huff=lib/foundry-huff/src/",
    "huffmate=lib/huffmate/src/",
]
fs_permissions = [
    { access = "read", path = "./src/ImmutableCreate2Factory.huff" },
    { access = "read", path = "./src/MetamorphicFactory.huff" },
    { access = "read", path = "./src/Metapod.huff" },
    { access = "read", path = "./src/TransientContract.huff" },
]
